// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Simulador_PlanMobileButton from "./islands/Simulador/PlanMobileButton.tsx";
import * as $Simulador_add_beneficiary from "./islands/Simulador/add-beneficiary.tsx";
import * as $Simulador_change_step_function from "./islands/Simulador/change-step-function.tsx";
import * as $Simulador_control_form_steps from "./islands/Simulador/control-form-steps.tsx";
import * as $Simulador_first_step_img from "./islands/Simulador/first-step-img.tsx";
import * as $Simulador_first_step_opt_btn from "./islands/Simulador/first-step-opt-btn.tsx";
import * as $Simulador_form_step_five from "./islands/Simulador/form-step-five.tsx";
import * as $Simulador_new_simulation_btn from "./islands/Simulador/new-simulation-btn.tsx";
import * as $Simulador_next_step_btn from "./islands/Simulador/next-step-btn.tsx";
import * as $Simulador_plan_card from "./islands/Simulador/plan-card.tsx";
import * as $Simulador_previous_step_btn from "./islands/Simulador/previous-step-btn.tsx";
import * as $Simulador_receive_contact_btn from "./islands/Simulador/receive-contact-btn.tsx";
import * as $Simulador_selected_plan from "./islands/Simulador/selected-plan.tsx";
import * as $Site_be_a_broker_form from "./islands/Site/be-a-broker-form.tsx";
import * as $Site_be_a_provider from "./islands/Site/be-a-provider.tsx";
import * as $Site_brokers_login_form from "./islands/Site/brokers-login-form.tsx";
import * as $Site_care_journey_card from "./islands/Site/care-journey-card.tsx";
import * as $Site_care_journey_island from "./islands/Site/care-journey-island.tsx";
import * as $Site_change_password from "./islands/Site/change-password.tsx";
import * as $Site_client_login_form from "./islands/Site/client-login-form.tsx";
import * as $Site_common_questions from "./islands/Site/common-questions.tsx";
import * as $Site_cookies_modal from "./islands/Site/cookies-modal.tsx";
import * as $Site_discover_differences from "./islands/Site/discover-differences.tsx";
import * as $Site_discover_our_plans from "./islands/Site/discover-our-plans.tsx";
import * as $Site_dpo_page from "./islands/Site/dpo-page.tsx";
import * as $Site_enterprise_login_form from "./islands/Site/enterprise-login-form.tsx";
import * as $Site_forgot_password from "./islands/Site/forgot-password.tsx";
import * as $Site_frequently_asked_questions from "./islands/Site/frequently-asked-questions.tsx";
import * as $Site_header_mobile_dropdown_sections from "./islands/Site/header-mobile-dropdown-sections.tsx";
import * as $Site_header_mobile_menu_btn from "./islands/Site/header-mobile-menu-btn.tsx";
import * as $Site_header_mobile_menu_dropdown from "./islands/Site/header-mobile-menu-dropdown.tsx";
import * as $Site_header_site from "./islands/Site/header-site.tsx";
import * as $Site_i_am_a_new_beneficiary from "./islands/Site/i-am-a-new-beneficiary.tsx";
import * as $Site_latest_news from "./islands/Site/latest-news.tsx";
import * as $Site_logged_areas_btn from "./islands/Site/logged-areas-btn.tsx";
import * as $Site_logged_areas_dropdown_menu from "./islands/Site/logged-areas-dropdown-menu.tsx";
import * as $Site_news_page_template from "./islands/Site/news-page-template.tsx";
import * as $Site_news_section from "./islands/Site/news-section.tsx";
import * as $Site_ombudsman_form from "./islands/Site/ombudsman-form.tsx";
import * as $Site_overlaid_news_banner from "./islands/Site/overlaid-news-banner.tsx";
import * as $Site_overlaid_video_section from "./islands/Site/overlaid-video-section.tsx";
import * as $Site_plans_section from "./islands/Site/plans-section.tsx";
import * as $Site_privacy_policies from "./islands/Site/privacy-policies.tsx";
import * as $Site_providers_login_form from "./islands/Site/providers-login-form.tsx";
import * as $Site_reels_section from "./islands/Site/reels-section.tsx";
import * as $Site_request_quote_form from "./islands/Site/request-quote-form.tsx";
import * as $Site_sales_section from "./islands/Site/sales-section.tsx";
import * as $Site_search_button_container from "./islands/Site/search-button-container.tsx";
import * as $Site_search_button from "./islands/Site/search-button.tsx";
import * as $Site_service_card_island from "./islands/Site/service-card-island.tsx";
import * as $Site_sliderjs from "./islands/Site/sliderjs.tsx";
import * as $Site_talk_to_us_form from "./islands/Site/talk-to-us-form.tsx";
import * as $Site_tour_section from "./islands/Site/tour-section.tsx";
import * as $Site_video_player from "./islands/Site/video-player.tsx";
import * as $Site_work_with_us_form from "./islands/Site/work-with-us-form.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Simulador/PlanMobileButton.tsx": $Simulador_PlanMobileButton,
    "./islands/Simulador/add-beneficiary.tsx": $Simulador_add_beneficiary,
    "./islands/Simulador/change-step-function.tsx":
      $Simulador_change_step_function,
    "./islands/Simulador/control-form-steps.tsx": $Simulador_control_form_steps,
    "./islands/Simulador/first-step-img.tsx": $Simulador_first_step_img,
    "./islands/Simulador/first-step-opt-btn.tsx": $Simulador_first_step_opt_btn,
    "./islands/Simulador/form-step-five.tsx": $Simulador_form_step_five,
    "./islands/Simulador/new-simulation-btn.tsx": $Simulador_new_simulation_btn,
    "./islands/Simulador/next-step-btn.tsx": $Simulador_next_step_btn,
    "./islands/Simulador/plan-card.tsx": $Simulador_plan_card,
    "./islands/Simulador/previous-step-btn.tsx": $Simulador_previous_step_btn,
    "./islands/Simulador/receive-contact-btn.tsx":
      $Simulador_receive_contact_btn,
    "./islands/Simulador/selected-plan.tsx": $Simulador_selected_plan,
    "./islands/Site/be-a-broker-form.tsx": $Site_be_a_broker_form,
    "./islands/Site/be-a-provider.tsx": $Site_be_a_provider,
    "./islands/Site/brokers-login-form.tsx": $Site_brokers_login_form,
    "./islands/Site/care-journey-card.tsx": $Site_care_journey_card,
    "./islands/Site/care-journey-island.tsx": $Site_care_journey_island,
    "./islands/Site/change-password.tsx": $Site_change_password,
    "./islands/Site/client-login-form.tsx": $Site_client_login_form,
    "./islands/Site/common-questions.tsx": $Site_common_questions,
    "./islands/Site/cookies-modal.tsx": $Site_cookies_modal,
    "./islands/Site/discover-differences.tsx": $Site_discover_differences,
    "./islands/Site/discover-our-plans.tsx": $Site_discover_our_plans,
    "./islands/Site/dpo-page.tsx": $Site_dpo_page,
    "./islands/Site/enterprise-login-form.tsx": $Site_enterprise_login_form,
    "./islands/Site/forgot-password.tsx": $Site_forgot_password,
    "./islands/Site/frequently-asked-questions.tsx":
      $Site_frequently_asked_questions,
    "./islands/Site/header-mobile-dropdown-sections.tsx":
      $Site_header_mobile_dropdown_sections,
    "./islands/Site/header-mobile-menu-btn.tsx": $Site_header_mobile_menu_btn,
    "./islands/Site/header-mobile-menu-dropdown.tsx":
      $Site_header_mobile_menu_dropdown,
    "./islands/Site/header-site.tsx": $Site_header_site,
    "./islands/Site/i-am-a-new-beneficiary.tsx": $Site_i_am_a_new_beneficiary,
    "./islands/Site/latest-news.tsx": $Site_latest_news,
    "./islands/Site/logged-areas-btn.tsx": $Site_logged_areas_btn,
    "./islands/Site/logged-areas-dropdown-menu.tsx":
      $Site_logged_areas_dropdown_menu,
    "./islands/Site/news-page-template.tsx": $Site_news_page_template,
    "./islands/Site/news-section.tsx": $Site_news_section,
    "./islands/Site/ombudsman-form.tsx": $Site_ombudsman_form,
    "./islands/Site/overlaid-news-banner.tsx": $Site_overlaid_news_banner,
    "./islands/Site/overlaid-video-section.tsx": $Site_overlaid_video_section,
    "./islands/Site/plans-section.tsx": $Site_plans_section,
    "./islands/Site/privacy-policies.tsx": $Site_privacy_policies,
    "./islands/Site/providers-login-form.tsx": $Site_providers_login_form,
    "./islands/Site/reels-section.tsx": $Site_reels_section,
    "./islands/Site/request-quote-form.tsx": $Site_request_quote_form,
    "./islands/Site/sales-section.tsx": $Site_sales_section,
    "./islands/Site/search-button-container.tsx": $Site_search_button_container,
    "./islands/Site/search-button.tsx": $Site_search_button,
    "./islands/Site/service-card-island.tsx": $Site_service_card_island,
    "./islands/Site/sliderjs.tsx": $Site_sliderjs,
    "./islands/Site/talk-to-us-form.tsx": $Site_talk_to_us_form,
    "./islands/Site/tour-section.tsx": $Site_tour_section,
    "./islands/Site/video-player.tsx": $Site_video_player,
    "./islands/Site/work-with-us-form.tsx": $Site_work_with_us_form,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
