// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Simulador/CompletedForm.tsx";
import * as $$$$$$1 from "./sections/Simulador/Footer.tsx";
import * as $$$$$$2 from "./sections/Simulador/FormStepFive.tsx";
import * as $$$$$$3 from "./sections/Simulador/FormStepFour.tsx";
import * as $$$$$$4 from "./sections/Simulador/FormStepOne.tsx";
import * as $$$$$$5 from "./sections/Simulador/FormStepThree.tsx";
import * as $$$$$$6 from "./sections/Simulador/FormStepTwo.tsx";
import * as $$$$$$7 from "./sections/Simulador/FormStepTwoforFourthOption.tsx";
import * as $$$$$$8 from "./sections/Simulador/Header.tsx";
import * as $$$$$$9 from "./sections/Simulador/ItWorks.tsx";
import * as $$$$$$10 from "./sections/Simulador/SecondStepOption1.tsx";
import * as $$$$$$11 from "./sections/Simulador/SecondStepOption2.tsx";
import * as $$$$$$12 from "./sections/Simulador/SimulatorContent.tsx";
import * as $$$$$$13 from "./sections/Simulador/ThirdStepOption1.tsx";
import * as $$$$$$14 from "./sections/Simulador/ThirdStepOption2.tsx";
import * as $$$$$$15 from "./sections/Site/AcceptanceTable.tsx";
import * as $$$$$$16 from "./sections/Site/BannerCarrousel.tsx";
import * as $$$$$$17 from "./sections/Site/BannerSection.tsx";
import * as $$$$$$18 from "./sections/Site/CareJourney.tsx";
import * as $$$$$$19 from "./sections/Site/ColorfullBanner.tsx";
import * as $$$$$$20 from "./sections/Site/ColorfullWrapper.tsx";
import * as $$$$$$21 from "./sections/Site/CommonQuestions.tsx";
import * as $$$$$$22 from "./sections/Site/DiscoverOurPlans.tsx";
import * as $$$$$$23 from "./sections/Site/Footer.tsx";
import * as $$$$$$24 from "./sections/Site/HeaderSite.tsx";
import * as $$$$$$25 from "./sections/Site/LatestNews.tsx";
import * as $$$$$$26 from "./sections/Site/MainServices.tsx";
import * as $$$$$$27 from "./sections/Site/MeetAurora.tsx";
import * as $$$$$$28 from "./sections/Site/NewsPage.tsx";
import * as $$$$$$29 from "./sections/Site/OmbudsmanForm.tsx";
import * as $$$$$$30 from "./sections/Site/PlansSection.tsx";
import * as $$$$$$31 from "./sections/Site/ProvidersSection.tsx";
import * as $$$$$$32 from "./sections/Site/RequestQuoteForm.tsx";
import * as $$$$$$33 from "./sections/Site/SideBySideContent.tsx";
import * as $$$$$$34 from "./sections/Site/SingleColorfullWrapper.tsx";
import * as $$$$$$35 from "./sections/Site/TalkToUsForm.tsx";
import * as $$$$$$36 from "./sections/Site/VideoSection.tsx";
import * as $$$$$$37 from "./sections/Site/WorkWithUsForm.tsx";
import * as $$$$$$38 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Simulador/CompletedForm.tsx": $$$$$$0,
    "site/sections/Simulador/Footer.tsx": $$$$$$1,
    "site/sections/Simulador/FormStepFive.tsx": $$$$$$2,
    "site/sections/Simulador/FormStepFour.tsx": $$$$$$3,
    "site/sections/Simulador/FormStepOne.tsx": $$$$$$4,
    "site/sections/Simulador/FormStepThree.tsx": $$$$$$5,
    "site/sections/Simulador/FormStepTwo.tsx": $$$$$$6,
    "site/sections/Simulador/FormStepTwoforFourthOption.tsx": $$$$$$7,
    "site/sections/Simulador/Header.tsx": $$$$$$8,
    "site/sections/Simulador/ItWorks.tsx": $$$$$$9,
    "site/sections/Simulador/SecondStepOption1.tsx": $$$$$$10,
    "site/sections/Simulador/SecondStepOption2.tsx": $$$$$$11,
    "site/sections/Simulador/SimulatorContent.tsx": $$$$$$12,
    "site/sections/Simulador/ThirdStepOption1.tsx": $$$$$$13,
    "site/sections/Simulador/ThirdStepOption2.tsx": $$$$$$14,
    "site/sections/Site/AcceptanceTable.tsx": $$$$$$15,
    "site/sections/Site/BannerCarrousel.tsx": $$$$$$16,
    "site/sections/Site/BannerSection.tsx": $$$$$$17,
    "site/sections/Site/CareJourney.tsx": $$$$$$18,
    "site/sections/Site/ColorfullBanner.tsx": $$$$$$19,
    "site/sections/Site/ColorfullWrapper.tsx": $$$$$$20,
    "site/sections/Site/CommonQuestions.tsx": $$$$$$21,
    "site/sections/Site/DiscoverOurPlans.tsx": $$$$$$22,
    "site/sections/Site/Footer.tsx": $$$$$$23,
    "site/sections/Site/HeaderSite.tsx": $$$$$$24,
    "site/sections/Site/LatestNews.tsx": $$$$$$25,
    "site/sections/Site/MainServices.tsx": $$$$$$26,
    "site/sections/Site/MeetAurora.tsx": $$$$$$27,
    "site/sections/Site/NewsPage.tsx": $$$$$$28,
    "site/sections/Site/OmbudsmanForm.tsx": $$$$$$29,
    "site/sections/Site/PlansSection.tsx": $$$$$$30,
    "site/sections/Site/ProvidersSection.tsx": $$$$$$31,
    "site/sections/Site/RequestQuoteForm.tsx": $$$$$$32,
    "site/sections/Site/SideBySideContent.tsx": $$$$$$33,
    "site/sections/Site/SingleColorfullWrapper.tsx": $$$$$$34,
    "site/sections/Site/TalkToUsForm.tsx": $$$$$$35,
    "site/sections/Site/VideoSection.tsx": $$$$$$36,
    "site/sections/Site/WorkWithUsForm.tsx": $$$$$$37,
    "site/sections/Theme/Theme.tsx": $$$$$$38,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
